apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  namespace: rabbitmq
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30072
    - name: http
      port: 15672
      targetPort: 15672
      nodePort: 30073
