apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer-scaler
  namespace: rabbitmq
spec:
  scaleTargetRef:
    name: rabbitmq-consumer
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: rabbitmq
      metadata:
        queueName: myqueue
        host: "amqp://user:QqQNcTYGaeNUpjDS@rabbitmq.rabbitmq.svc.cluster.local:5672/"
        queueLength: "5"
